name: Swap Blue Green

on:
  workflow_dispatch:

jobs:
  swap:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Swap Elastic Beanstalk CNAMEs
        run: |
          aws elasticbeanstalk swap-environment-cnames \
            --source-environment-name "3tier-beanstalk-dev" \
            --destination-environment-name "3tier-beanstalk-green"